version: "3.9"

services:
  # web:
  #   build: .
  #   container_name: flask_app
  #   restart: always
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   environment:
  #     USER_DB: ${USER_DB}
  #     PASSWORD_DB: ${PASSWORD_DB}
  #     URL_DB: ${URL_DB}
  #     DB: ${DB}

  db:
    image: mysql:8.0
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASSWORD_DB}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
