"""test

Revision ID: e4290a1c3f26
Revises: 294416d17e89
Create Date: 2025-09-23 20:57:11.727744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4290a1c3f26'
down_revision: Union[str, Sequence[str], None] = '294416d17e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('password'), table_name='users')
    op.drop_index(op.f('username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('description'), table_name='projects')
    op.drop_index(op.f('github_link'), table_name='projects')
    op.drop_index(op.f('link'), table_name='projects')
    op.drop_index(op.f('name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('github_link', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('link', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('link'), 'projects', ['link'], unique=True)
    op.create_index(op.f('github_link'), 'projects', ['github_link'], unique=True)
    op.create_index(op.f('description'), 'projects', ['description'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_index(op.f('password'), 'users', ['password'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
